
Bickerton, D. (1991). Language & species. Chicago, IL: Univ. of Chicago Press.
* Introduction
Bickerton asserts that humans gained advantage over other animals not only through consciousness and power over nature, but importantly and perhaps primarily through our use of language. He claims that it is difficult to reflect upon language as we do our other capacities, and so we are still in the infancy of learning the power that language has afforded our mental abilities.
* Chapter 1
Bickerton first approaches what he calls the "Continuity Paradox" in which language of humans is qualitatively different than language of any other terrestrial species. The paradox enters when we try to examine language as an artifact of natural selection. If language evolved, then it must have evolved from something. However, the communication systems of other animals pale in comparison to those of humans. From bees to chimps to dolphins, animals have adapted forms of communications, but studies of each suggest that communications are holistic and not generative. The holistic interpretation means that meaning is found only in utterances rather than lexical or grammatical constructions. So, animals can say "Look out, a snake!" or "Look  out, an eagle", but they can't simply say "a snake" or "an eagle". This means they are unable to reuse parts of their language in generative ways to form new meanings.

Humans, on the other hand, are able to reuse language parts and re-contextualize them to form new meanings. So we can move from "Look out, a snake!" to "Look, a snake" to "A snake looks". By separating an utterance into reusable parts, humans can form infinite meanings. This is qualitatively different from the animal utterances, which are bound by their environment, their perceptions, and their immediate concepts.

Bickerton posits that the movement toward lexical and grammatical language and away from holistic utterances was made possible by cognitive and conceptual changes having to do with representation. By focusing on representation, Bickerton side-steps the continuity paradox of communication systems. Communication systems must be studied from a social perspective, as there is no meaning outside use. Bickerton notes that there has also been significant progress in formal studies of language, which has illuminated the basic structures universal in all language. He suggests that the formal structures are the underpinnings of language that allow it to be used as a communication system in a social context. Therefore, the roots of language are actually representational, rather than communicative. Humans developed systems for representing entities and things predicated on entities.

So, we can categorize things in the world, and describe their attributes and what they do. Entities and what they do form the bulk of lexical items of language, and grammatical structures form much of the rest. The first category is "things in the world" and the second is "how to relate them with language". Syntactic structures work on ontological systems in order to make sense of the world. Bickerton thinks this jump is what sets humans apart from other animals, but the move is now much smaller from animal representation to human representation. Several animal examples show that animals can also represent categories of different kinds in their own communication systems. Humans have simply codified representations into grammatical structures. Once uttered, representation becomes communication.

* Chapter 2

After the introductory chapter, Bickerton takes a deep dive into his theory of representation, including its links to language, its mirrors in animals, carving semantic space, and organization in hierarchies.

The author starts with a metaphor of language as both map and itinerary for representation. It is a map in the way it abstracts concepts from actual things, and the way language is an itinerary is left to Chapter 3. On the map end, a picture is a representation of an object or even. Bickerton gives the example of a painting of a battle, where the battle may be recognizable, but its medium, scent, sounds, and other details are all missing. Still, we can recognize the same concept.

Of course, mapping reality onto concepts is something animals can also do. Bickerton notes that animals can sound alarms without seeing entire animals, but only hints or pieces. This means that they must have some concept of e.g. /leopard/ without specifically an entity of a leopard present. Further, animals merge multi-sensory aspects into one a single entity for their concept and reaction. That is, the sight, sound, and scent all come together to inform animals that something is a leopard.

Humans do similar mapping to concrete entities like leopards, but we have also been able to create abstract entities like burglar, abstract concepts like paranoia, or totally made-up concepts like unicorns. Burglars and paranoia as concepts rely on other social concepts like property and ownership or mental state and persecution. The unicorn concept requires breaking down parts of real concepts (horse body and narwhal horn) and putting them together into a concept without incorporation.

Many words and concepts are functionally derived. Bickerton gives the example of trees and bushes. The physical properties that separate the two concepts are very blurry. Some trees are short with many branches. Some bushes are tall with only a few branches. However, in general trees can be climbed, or may eventually be big enough to do so. Bushes, on the other hand, can be used to hide in, or at least could be if they grow properly. We can see that burglar has social function, as does paranoia. Unicorns also have social function in storytelling and mythology.

Of course, the language structure and conceptual maps aren't without their limitations and guidelines. Linguistics studies of the past few decades have shown that semantic maps are far from arbitrary. For example, existence, location, possession and ownership map onto the English verbs "to be" or "to have". Other languages divvy up these concepts differently, but some combinations never occur. These types of regularities are pervasive when examining languages throughout the world.

* Chapter 3
Continuing with the map and itinerary metaphor, Bickerton explores the itinerary side of language in Chapter 3. Beyond referring with nouns and verbs, language also describes these references and also gives expression structure. The structure of language boils down to three main points: predicability, grammatization, and syntax.

Predicability is the way that we use language descriptively. It allows us to make categorical statements, like "a dog is a mammal", ", descriptive statements, like "the grass is green", and metaphorical statements, like "money is the root of all evil. Predicability also constrains language, in the categories it imposes. So, while "the grass is green" makes sense, "the idea is green" does not. So, language employs predicability to functionally categorize objects and actions. We can then exploit these categories to highlight relationships through metaphor. In this way, evil can have roots, or familiarity can breed (contempt).

Grammatization inserts information into language when it seems like it coule be optional. Bickerton cites Willard Quine specifically being perplexed at the necessity of tense in expression. It is just one example of information that must be included in English to make grammatical sentences. We cannot avoid marking tense, just as speakers of other language cannot avoid marking gender, agency or epistemics. Of course, these distinctions aren't always obligatory in the way that tense is, but some still find their way into language through prepositions (above, below, in), modal markers (usually, possibly, necessarily), or direction (to, up, left). 

An interesting component of grammaticized language is its functional orientation. Like Bickerton's story of lexical items forming through function, grammatical also shows signs of functionalism in the way that it orients itself to relative comparison. For example, most prepositional phrases are relative. For example, "next to the fridge" and "next to the mountain" are much different areas of precision, each relative to the size of the referent rather than the "next to the" grammatical phrasing.

Finally, Bickerton considers syntax and the structure of phrases and sentences. Predicability and grammar inform syntax, of course. There are sentences that don't parse syntactically because of predicate violations (e.g. ideas can't sleep) or grammar violations (e.g. something can be "on the left" but not "under the left"). But these are only aspects of syntax, which also includes word order, phrase order, phrase structure, and more. "The left to" or "sleep ideas" are meaningless in different ways than the previous violations since their word order does not follow convention. Expanding from phrases, "Sue left Tom" has a different meaning than "Tom left Sue", even with the same words. These syntactic forms are pervasive in English and have shown up in all languages that have been studied. This suggests that there is a deeper level of organization in language that universally informs linguistic thought. 

Further, the so called "universal grammar" gives language it's combinatoric power where the lexicon can employ a standard structure in order to express endless thoughts with finite words. Humans can count on the structure to inform the parsing and provide an itenerary through the lexical ideas found in phrases or sentences.
